language: python
sudo: false
python:
  - "2.7"
  - "3.4"
services:
- elasticsearch
before_script:
  - sleep 10
env:
  - DJANGO_REQUIREMENT="Django>=1.4,<1.5"
  - DJANGO_REQUIREMENT="Django==1.8"
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_REQUIREMENT="Django>=1.4,<1.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q $DJANGO_REQUIREMENT elasticsearch django-haystack django-modeltranslation flake8 --use-mirrors
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script:
  - cd tests
  - flake8 .
  - if [[ $DJANGO_REQUIREMENT == "Django==1.8" ]]; then export TARGET="tests"; fi
  - if [[ $DJANGO_REQUIREMENT == "Django>=1.4,<1.5" ]]; then export TARGET="testproject"; fi
  - ./manage.py test $TARGET